name: Say Hello World
on:
  issues:
    types:
      - opened
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Probot app name
        uses: maximilianone/add-task-issue-labels@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
