name: Task Issue Labeler
on:
  issues:
    types:
      - opened
jobs:
  Label-New-Issues:
    runs-on: ubuntu-latest
    steps:
      - name: Set issue label
        uses: maximilianone/add-task-issue-labels@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
